ERROR - 2025-10-01 23:27:15 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'gestorv2', 3306, '', 0)
#1 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\app\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
#7 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#8 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\Users\\HomeUs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\app\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
#6 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#7 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\Users\\HomeUs...')
#13 {main}
CRITICAL - 2025-10-01 23:27:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `email` = :email:
AND `usuarios`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(715): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\Users\\HomeUser\\Desktop\\DEVELOPER\\GestorV2\\backend\\public\\index.php')
ERROR - 2025-10-01 23:28:06 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'gestorv2', 3306, '', 0)
#1 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\app\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
#7 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#8 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\Users\\HomeUs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\app\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
#6 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#7 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\Users\\HomeUs...')
#13 {main}
CRITICAL - 2025-10-01 23:28:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `email` = :email:
AND `usuarios`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(715): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\Users\\HomeUser\\Desktop\\DEVELOPER\\GestorV2\\backend\\public\\index.php')
ERROR - 2025-10-01 23:28:25 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'gestorv2', 3306, '', 0)
#1 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\app\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
#7 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#8 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\Users\\HomeUs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\app\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
#6 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#7 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\Users\HomeUser\Desktop\DEVELOPER\GestorV2\backend\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\Users\\HomeUs...')
#13 {main}
CRITICAL - 2025-10-01 23:28:25 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `email` = :email:
AND `usuarios`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(715): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\AuthController.php(35): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\Users\\HomeUser\\Desktop\\DEVELOPER\\GestorV2\\backend\\public\\index.php')
